### PR TITLE
Add hare

### PR DESCRIPTION
**Pull request by aude**
Add support for Hare: https://harelang.org/

### CODE REVIEW

**Comment by aude** [comment]
Don't think Hare has an SVG logo, made one with:
```
$ convert hare.png hare.pnm
$ potrace -s -t 0 -a 0 -n -O 0 -u 1 -W 256 -H 256 -x 1 -o hare.svg hare.svg.pnm
```

**Comment by aude** [comment]
> Hare source files MUST be indented with tabs. The tab size SHOULD be 8 columns.
> https://harelang.org/style/#a-general-conventions

So I set `useSoftTabs = False`, seems to be the first language trying it out FYI

**Comment by prasmussen** [comment]
> Don't think Hare has an SVG logo, made one with:
> 
> ```
> $ convert hare.png hare.pnm
> $ potrace -s -t 0 -a 0 -n -O 0 -u 1 -W 256 -H 256 -x 1 -o hare.svg hare.svg.pnm
> ```

The svg looks pretty good actually

**Comment by prasmussen** [comment]
> > Hare source files MUST be indented with tabs. The tab size SHOULD be 8 columns.
> > https://harelang.org/style/#a-general-conventions
> 
> So I set `useSoftTabs = False`, seems to be the first language trying it out FYI

Hehe, I don't think it's actually implemented in the code yet. Will take a look

**Comment by prasmussen** [comment]
Deployed

**Pull request merged**
